model_name: "PEGVAE"
resume_training_from_ckpt:
  path:
pl_config:
  requires_dense: True
  batch_size: 64
  lr: 1e-4
  kl_config:
    start_kl_loss_phasing: 12000
    kl_weight: 1.0e-04
    max_kl_weight: 0.5
    kl_weight_step: 1.0e-04
  model_config:
    riemannian: False
    encoder_config:
      node_features: 10
      edge_features: 3
      latent_dim: 1
      filter_channels: 20
    decoder_config:
      node_features: 10
      edge_features: 3
      latent_dim: 1
      filter_channels: 20
      node_threshold: 0.54
      edge_threshold: 0.04
