model_name: GraphClassifier
pl_config:
  requires_dense: True
  batch_size: 16
  lr: 1e-4
  model_config:
    riemannian: False
    node_features: 3
    edge_features: 1
    num_classes: 2
    num_layers: 3
    filter_channels: 20
